repositories:
  - name: main
    path: .
    type: GIT
    branch: main
    testPaths:
      - "**/src/test/**"
    excludePaths:
      - "**/build/**"
      - "**/target/**"
      - "**/node_modules/**"

domainMappings:
  - domainId: core
    pathPatterns:
      - "**/impacto-core/**"
    featureMappings:
      - featureId: git-analysis
        pathPatterns:
          - "**/impacto-core/src/main/kotlin/com/multiplier/impacto/core/git/**"
        componentMappings:
          - componentId: git-diff
            pathPatterns:
              - "**/impacto-core/src/main/kotlin/com/multiplier/impacto/core/git/diff/**"
          - componentId: git-repository
            pathPatterns:
              - "**/impacto-core/src/main/kotlin/com/multiplier/impacto/core/git/repository/**"

  - domainId: domain
    pathPatterns:
      - "**/impacto-domain/**"
    featureMappings:
      - featureId: domain-model
        pathPatterns:
          - "**/impacto-domain/src/main/kotlin/com/multiplier/impacto/domain/model/**"
        componentMappings:
          - componentId: code-entity
            pathPatterns:
              - "**/impacto-domain/src/main/kotlin/com/multiplier/impacto/domain/model/CodeEntity.kt"
          - componentId: test-entity
            pathPatterns:
              - "**/impacto-domain/src/main/kotlin/com/multiplier/impacto/domain/model/TestEntity.kt"
          - componentId: domain-entity
            pathPatterns:
              - "**/impacto-domain/src/main/kotlin/com/multiplier/impacto/domain/model/DomainEntity.kt"

scoringConfig:
  weights:
    IMPORT_OVERLAP: 0.3
    PACKAGE_SIMILARITY: 0.2
    ANNOTATION_MATCH: 0.2
    HISTORICAL_DATA: 0.3
  thresholds:
    HIGH: 0.8
    MEDIUM: 0.5
    LOW: 0.2

botConfig:
  name: Impacto
  language: en
  templates:
    REPORT_HEADER: "# Test Impact Analysis Report\n\nGenerated by Impacto on {{date}}\n\n"
    REPORT_FOOTER: "\n\n## Summary\n\nTotal tests: {{totalTests}}\nHigh confidence: {{highConfidence}}\nMedium confidence: {{mediumConfidence}}\nLow confidence: {{lowConfidence}}\n"

outputConfig:
  format: MARKDOWN
  outputPath: impacto-report
  includeDetails: true
  groupBy: DOMAIN
